sudo: false

language: go

go:
  - 1.6
  - tip

install:
  - go get -t -v github.com/tehnerd/gnl2go
  - go get -t -v ./...

script:
  - ./.travis/script.sh . core disco pulse util gorb-docker-link

after_success:
  - bash <(curl -s https://codecov.io/bash)
