sudo: false

language: go

go:
  - 1.6
  - tip

install:
  - go get -t ./...

script:
  - ./.travis/script.sh . core disco pulse util gorb-docker-link

after_success:
  - bash <(curl -s https://codecov.io/bash)
