language: go

go:
  - 1.5
  - tip

install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/stretchr/testify/require
  - go get github.com/gorilla/mux
  - go get github.com/sirupsen/logrus
  - go get github.com/tehnerd/gnl2go

script:
  - ./.travis/script.sh . core pulse util

after_success:
  - bash <(curl -s https://codecov.io/bash)
